use crate::span::Span;

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum TokenKind {
    Ident(String),
    Integer(String),
    Float(String),
    String(String),
    Char(char),
    Newline,
    Whitespace,
    Comment,
    At,
    KeywordUse,
    KeywordEdition,
    KeywordRationale,
    KeywordCap,
    KeywordDef,
    KeywordFn,
    KeywordIf,
    KeywordThen,
    KeywordElse,
    KeywordElsif,
    KeywordWhile,
    KeywordStruct,
    KeywordEnum,
    KeywordMatch,
    KeywordWhen,
    KeywordTrait,
    KeywordImpl,
    KeywordFor,
    KeywordIn,
    KeywordDo,
    KeywordLet,
    KeywordMut,
    KeywordReturn,
    KeywordBreak,
    KeywordNext,
    KeywordPub,
    KeywordModule,
    KeywordMod,
    KeywordConst,
    KeywordType,
    KeywordExtern,
    KeywordWhere,
    KeywordAs,
    KeywordSuper,
    KeywordCrate,
    KeywordYield,
    KeywordAsync,
    KeywordAwait,
    KeywordRequires,
    KeywordEffect,
    KeywordImplies,
    KeywordHandle,
    KeywordWith,
    KeywordBudget,
    KeywordPre,
    KeywordPost,
    KeywordInvariant,
    KeywordGuard,
    KeywordTry,
    KeywordCatch,
    KeywordFinally,
    KeywordMacro,
    KeywordComptime,
    KeywordLoop,
    KeywordPure,
    KeywordInline,
    KeywordUnless,
    KeywordUntil,
    KeywordUnsafe,
    KeywordEnd,
    KeywordTrue,
    KeywordFalse,
    KeywordSelfValue,
    KeywordSelfTy,
    KeywordDyn,
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    ColonColon,
    Colon,
    Comma,
    Dot,
    DotDot,
    DotDotEq,
    Semi,
    Arrow,
    FatArrow,
    EqEq,
    Bang,
    BangEq,
    Lt,
    LtEq,
    Gt,
    GtEq,
    Amp,
    AmpAmp,
    Pipe,
    PipePipe,
    Caret,
    Tilde,
    Shl,
    Shr,
    Plus,
    Minus,
    Slash,
    Percent,
    Star,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    PercentEq,
    Eq,
    Question,
    Eof,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub lexeme: String,
    pub span: Span,
}

impl Token {
    #[must_use]
    pub fn new(kind: TokenKind, lexeme: impl Into<String>, span: Span) -> Self {
        Self {
            kind,
            lexeme: lexeme.into(),
            span,
        }
    }
}
