(lang dune 3.0)
(using menhir 2.1)
(name tg_stage0)
(version 0.1.0)

(generate_opam_files true)

(source (github tangerine-lang/tangerine))
(license MIT)
(authors "Tangerine Team")
(maintainers "team@tangerine-lang.org")

(package
 (name tg_stage0)
 (synopsis "Tangerine Stage0 Bootstrap Compiler")
 (description "Bootstrap compiler for Tangerine, written in OCaml. Used to compile the self-hosting Tangerine compiler.")
 (depends
  (ocaml (>= 4.14))
  dune
  menhir
  yojson
  cmdliner))
