#!/usr/bin/env bash
#
# scripts/check_grammar_f_gate.sh — Gate F: the grammar-production coverage
# oracle.
#
# The oracle: the grammar facts (docs/current/grammar_facts.toml — the
# production enumeration derived from docs/current/grammar.md's EBNF rule
# set) vs the tests' programs (tests/grammar_f/). Every production must
# carry FOUR specimens, all generated by
# scripts/gen_grammar_f_specimens.py:
#   pos/<prod>_minimal.tg     minimal positive (the construct alone)
#   pos/<prod>_nested.tg      positive with the construct NESTED inside
#                             another construct
#   neg/<prod>_before.tg      the minimal positive with the production's
#                             OWN grammar violation (the per-production
#                             malformation catalog — the wrong arity / the
#                             wrong keyword / the missing clause — NOT the
#                             generic stray paren) placed BEFORE the
#                             construct — the parser must still reject the
#                             program (the construct cannot swallow the
#                             error)
#   neg/<prod>_after.tg       the same production-specific malformation
#                             placed AFTER the construct — the parser must
#                             still reject the program (the construct
#                             cannot swallow what follows)
#
# The reviewer's item 10 strengthening: the generic stray-paren negative
# is FORBIDDEN — a bare `)` line in any negative specimen fails the gate
# (the malformations must be the production's own grammar violations).
#
# WHAT THE GATE CHECKS
#   1. FACTS ↔ FILES parity — every production in the facts has its four
#      specimen files and every file maps back to a production (the
#      regenerate-then-diff discipline: the corpus is regenerated into a
#      temp dir and diffed byte-for-byte against tests/grammar_f).
#   2. SPECIMEN STRUCTURE — the positive files carry the declared marker
#      (`# gate-f: <prod> minimal-positive` / `nested-positive`) and the
#      negative files carry the invalid-before/invalid-after markers with
#      the malformation block (`# gate-f: <prod> malformed`) positioned
#      BEFORE/AFTER the construct marker (a mechanical, position-verified
#      property), plus the generic-stray-paren backstop (a bare `)` line
#      is a failure).
#   3. COMPILER VERDICTS (when a USABLE compiler binary exists — the same
#      probe discipline as run_selfhost_grammar_gate.sh: the binary must
#      accept a valid probe and REJECT a broken probe):
#        verify=check productions:  positives must pass `check`
#        verify=parse productions:  positives must pass `parse` (the
#                                   pipeline rejects them AFTER parsing by
#                                   design — try_expr / handle_with_expr)
#        all negatives:             `check` must fail (a diagnostic must
#                                   appear — the bootstrap ladder rule)
#      Without a usable binary the structural checks (1 + 2) remain the
#      authoritative rejection OUTSIDE the release context.
#
# THE RELEASE CONTEXT (--release): the reviewer's item 10 release-path
# requirement — the compiler-verdict layer is REQUIRED. In the release
# context a missing usable binary FAILS the gate with the
# PENDING-UNTIL-BINARY verdict (the release proof's Gate-F row reads
# PENDING-UNTIL-BINARY until the ladder produces a current-grammar stage
# binary); the structural-only pass is never a release pass. --report-only
# can never mask a failure in the release context.
#
# Usage: scripts/check_grammar_f_gate.sh [--report-only] [--release]
# Exit status: 0 when every production's four specimens exist, regenerate
# identically, carry the right structure, and (with a usable compiler)
# receive the right verdicts; 1 otherwise. In the release context the
# compiler-verdict layer is required (a missing binary is a FAIL with the
# PENDING-UNTIL-BINARY verdict).

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FACTS="$ROOT/docs/current/grammar_facts.toml"
GEN="$ROOT/scripts/gen_grammar_f_specimens.py"
SUITE="$ROOT/tests/grammar_f"
BUILD_DIR="$ROOT/build"
REPORT_ONLY=0
RELEASE=0
while [ $# -gt 0 ]; do
  case "$1" in
    --report-only) REPORT_ONLY=1 ;;
    --release) RELEASE=1 ;;
    *) echo "check_grammar_f_gate: unknown argument: $1" >&2; exit 2 ;;
  esac
  shift
done

fail() { echo "[grammar-f:error] $*" >&2; exit 1; }

[ -f "$FACTS" ] || fail "missing grammar facts: $FACTS"
[ -f "$GEN" ] || fail "missing specimen generator: $GEN"
[ -d "$SUITE" ] || fail "missing specimen suite: $SUITE"

# ———————————————————————————————————————————————————————————————
# 1. FACTS ↔ FILES parity — regenerate into a temp dir and diff.
# ———————————————————————————————————————————————————————————————

TMP="$(mktemp -d "${TMPDIR:-/tmp}/grammar_f_gate.XXXXXX")"
DIFF_OUT="$(mktemp "${TMPDIR:-/tmp}/grammar_f_gate_diff.XXXXXX")"
trap 'rm -rf "$TMP" "$DIFF_OUT"' EXIT

if ! python3 "$GEN" --out "$TMP" >/dev/null 2>&1; then
  fail "generator failed — a facts production has no specimen templates (the uncovered productions get the specimens, never a silent skip)"
fi

if ! diff -r "$TMP" "$SUITE" >"$DIFF_OUT" 2>&1; then
  echo "[grammar-f:error] tests/grammar_f/ does not match a fresh generation (the generate-then-diff discipline):"
  head -40 "$DIFF_OUT"
  fail "regeneration parity FAILED — regenerate with scripts/gen_grammar_f_specimens.py"
fi

# ———————————————————————————————————————————————————————————————
# 2. The per-production specimen structure.
# ———————————————————————————————————————————————————————————————

# production names + verify modes from the facts (TOML: [production.X]).
productions="$(awk '/^\[production\./ { name = $0; sub(/^\[production\./, "", name); sub(/\]$/, "", name); print name }' "$FACTS" | sort)"
count="$(printf '%s\n' "$productions" | grep -c .)"
[ "$count" -gt 0 ] || fail "facts file lists no productions"

verify_of() {
  # verify mode of a production (default check)
  awk -v p="production.$1" '
    $0 == "[" p "]" { found = 1; next }
    found && /^verify[ \t]*=/ { sub(/^verify[ \t]*=[ \t]*"/, ""); sub(/".*$/, ""); print; exit }
  ' "$FACTS"
}

structure_bad=0
while IFS= read -r prod; do
  [ -n "$prod" ] || continue
  pos_min="$SUITE/pos/${prod}_minimal.tg"
  pos_nest="$SUITE/pos/${prod}_nested.tg"
  neg_before="$SUITE/neg/${prod}_before.tg"
  neg_after="$SUITE/neg/${prod}_after.tg"
  for f in "$pos_min" "$pos_nest" "$neg_before" "$neg_after"; do
    [ -f "$f" ] || { echo "[grammar-f:error] $prod: missing specimen: $f"; structure_bad=1; }
  done
  [ "$structure_bad" -eq 1 ] && continue
  # positive markers
  grep -q "# gate-f: $prod minimal-positive" "$pos_min" || { echo "[grammar-f:error] $prod: minimal-positive marker missing"; structure_bad=1; }
  grep -q "# gate-f: $prod nested-positive" "$pos_nest" || { echo "[grammar-f:error] $prod: nested-positive marker missing"; structure_bad=1; }
  # negative markers + the positional property: the production-specific
  # malformation block (the production's OWN grammar violation — the
  # wrong arity / the wrong keyword / the missing clause) sits BEFORE
  # the construct marker in the before file and AFTER it in the after
  # file. The generic stray-paren negative is FORBIDDEN (the reviewer's
  # item 10): a bare `)` line in any negative specimen is a failure.
  grep -q "# gate-f: $prod invalid-before" "$neg_before" || { echo "[grammar-f:error] $prod: invalid-before marker missing"; structure_bad=1; }
  grep -q "# gate-f: $prod invalid-after" "$neg_after" || { echo "[grammar-f:error] $prod: invalid-after marker missing"; structure_bad=1; }
  grep -q '^)$' "$neg_before" && {
    echo "[grammar-f:error] $prod: invalid-before specimen uses the generic stray-paren negative — the negatives must be the production-specific malformations (wrong arity / wrong keyword / missing clause), never a bare ')'"
    structure_bad=1
  }
  grep -q '^)$' "$neg_after" && {
    echo "[grammar-f:error] $prod: invalid-after specimen uses the generic stray-paren negative — the negatives must be the production-specific malformations (wrong arity / wrong keyword / missing clause), never a bare ')'"
    structure_bad=1
  }
  before_mal="$(grep -n "# gate-f: $prod malformed" "$neg_before" | head -1 | cut -d: -f1)"
  before_marker="$(grep -n "# gate-f: $prod minimal-positive" "$neg_before" | head -1 | cut -d: -f1)"
  [ -n "$before_mal" ] && [ -n "$before_marker" ] && [ "$before_mal" -lt "$before_marker" ] || {
    echo "[grammar-f:error] $prod: invalid-before specimen must place the malformation BEFORE the construct (malformed marker line $before_mal vs construct marker line $before_marker)"
    structure_bad=1
  }
  after_mal="$(grep -n "# gate-f: $prod malformed" "$neg_after" | head -1 | cut -d: -f1)"
  after_marker="$(grep -n "# gate-f: $prod minimal-positive" "$neg_after" | head -1 | cut -d: -f1)"
  [ -n "$after_mal" ] && [ -n "$after_marker" ] && [ "$after_mal" -gt "$after_marker" ] || {
    echo "[grammar-f:error] $prod: invalid-after specimen must place the malformation AFTER the construct (malformed marker line $after_mal vs construct marker line $after_marker)"
    structure_bad=1
  }
done <<< "$productions"

if [ "$structure_bad" -ne 0 ]; then
  if [ "$RELEASE" -eq 1 ]; then
    echo "[grammar-f] GATE-F|FAIL|structural failures above — the release context REQUIRES the full gate (report-only can never mask a release failure)"
    exit 1
  fi
  [ "$REPORT_ONLY" -eq 1 ] || exit 1
fi

# ———————————————————————————————————————————————————————————————
# 3. Compiler verdicts — with a USABLE binary (accepts a valid probe,
#    rejects a broken probe). WITHOUT one the structural checks remain
#    the authority OUTSIDE the release context; the RELEASE context
#    (--release) REQUIRES the compiler-verdict layer — a missing usable
#    binary is the PENDING-UNTIL-BINARY verdict (a FAIL: the release
#    proof's Gate-F row stays PENDING-UNTIL-BINARY until the ladder
#    produces a current-grammar stage binary).
# ———————————————————————————————————————————————————————————————

GOOD_PROBE="$TMP/gate_f_good.tg"
BAD_PROBE="$TMP/gate_f_bad.tg"
CURRENT_PROBE="$TMP/gate_f_current.tg"
cat > "$GOOD_PROBE" <<'EOF'
def gate_f_good_probe() -> Int
  0
end
EOF
cat > "$BAD_PROBE" <<'EOF'
def gate_f_bad_probe( -> Int
  0
end
EOF
# The current-grammar probe: the constructs the bootstrap canaries use
# (the access conventions, the capability decl, the resource finalizer) —
# a STALE binary (built before the current grammar) rejects it and is
# NOT usable for the compiler-verdict layer (its failures would be false
# negatives on current constructs).
cat > "$CURRENT_PROBE" <<'EOF'
use std::core

def gate_f_probe_inc(inout x: Int) -> Int
  x + 1
end

cap GateFProbeCap
end

resource GateFProbeResource
  v: Int

  def deinit(sink self: Self) -> Unit
    ()
  end
end

def gate_f_current_probe() -> Int
  var x = 0
  gate_f_probe_inc(x)
  0
end
EOF

probe_check() {
  ( "$1" check "$2" >/dev/null 2>&1; exit $? ) 2>/dev/null
}

BIN=""
for cand in tg_stage3 tg_stage2 tg_stage1; do
  [ -x "$BUILD_DIR/$cand" ] || continue
  cand_bin="$BUILD_DIR/$cand"
  if probe_check "$cand_bin" "$GOOD_PROBE" && ! probe_check "$cand_bin" "$BAD_PROBE" &&
     probe_check "$cand_bin" "$CURRENT_PROBE"; then
    BIN="$cand_bin"
    break
  fi
done

check_fail() {
  # the bootstrap ladder rule: a rejection is a non-zero exit OR a
  # diagnostic on the output ("error|parse|expected|syntax").
  local out
  out="$("$1" check "$2" 2>&1)"
  if [ $? -ne 0 ]; then
    return 0
  fi
  printf '%s\n' "$out" | grep -qi 'error\|parse\|expected\|syntax'
}

echo "[grammar-f] productions: $count"
printf '%-26s %-8s %-9s %-8s %-8s %-7s %s\n' "PRODUCTION" "VERIFY" "MINIMAL" "NESTED" "BEFORE" "AFTER" "NOTES"
bad=0
if [ -z "$BIN" ]; then
  if [ "$RELEASE" -eq 1 ]; then
    echo "[grammar-f] GATE-F|PENDING-UNTIL-BINARY|the release context REQUIRES the compiler-verdict layer — no usable stage binary in $BUILD_DIR (the ladder must produce a current-grammar binary; the structural pass is never a release pass)"
    exit 1
  fi
  while IFS= read -r prod; do
    [ -n "$prod" ] || continue
    printf '%-26s %-8s %-9s %-8s %-8s %-7s %s\n' "$prod" "$(verify_of "$prod")" "OK" "OK" "OK" "OK" "compiler skipped (no usable binary)"
  done <<< "$productions"
  echo "[grammar-f] NO usable compiler binary — structural gate only (bootstrap will produce one; the release context requires the verdicts)"
  exit 0
fi

echo "[grammar-f] compiler: $BIN (current grammar confirmed by probe rejection)"
while IFS= read -r prod; do
  [ -n "$prod" ] || continue
  verify="$(verify_of "$prod")"
  min_v="OK"
  nest_v="OK"
  bef_v="OK"
  aft_v="OK"
  note=""
  pos_min="$SUITE/pos/${prod}_minimal.tg"
  pos_nest="$SUITE/pos/${prod}_nested.tg"
  neg_before="$SUITE/neg/${prod}_before.tg"
  neg_after="$SUITE/neg/${prod}_after.tg"

  if [ "$verify" = "parse" ]; then
    # parse-only productions: the positives must PARSE; check may reject
    # them by design (the pipeline rejects them after parsing).
    "$BIN" parse "$pos_min" >/dev/null 2>&1 || { min_v="FAIL"; bad=1; }
    "$BIN" parse "$pos_nest" >/dev/null 2>&1 || { nest_v="FAIL"; bad=1; }
    note="parse-level (pipeline-rejected after parse by design)"
  else
    "$BIN" check "$pos_min" >/dev/null 2>&1 || { min_v="FAIL"; bad=1; }
    "$BIN" check "$pos_nest" >/dev/null 2>&1 || { nest_v="FAIL"; bad=1; }
  fi
  check_fail "$BIN" "$neg_before" || { bef_v="FAIL"; bad=1; }
  check_fail "$BIN" "$neg_after" || { aft_v="FAIL"; bad=1; }

  printf '%-26s %-8s %-9s %-8s %-8s %-7s %s\n' "$prod" "$verify" "$min_v" "$nest_v" "$bef_v" "$aft_v" "$note"
done <<< "$productions"

if [ "$bad" -ne 0 ]; then
  if [ "$RELEASE" -eq 1 ]; then
    echo "[grammar-f] GATE-F|FAIL|compiler-verdict failures above — the release context REQUIRES the verdicts from the actual compiler execution (report-only can never mask a release failure)"
    exit 1
  fi
  [ "$REPORT_ONLY" -eq 1 ] || exit 1
  echo "[grammar-f] FAILURES above (report-only)"
  exit 0
fi
if [ "$RELEASE" -eq 1 ]; then
  echo "[grammar-f] GATE-F|PASS|all $count productions: the four specimens exist, regenerate identically, and the ACTUAL compiler execution returned the required verdicts"
fi
echo "[grammar-f] GATE F PASSED: every production's four specimens exist, regenerate identically, and receive the right compiler verdicts"
exit 0
