#!/usr/bin/env bash
#
# scripts/gen_feature_registry.sh — generate docs/current/feature_registry.md
# from the machine-readable features.toml.
#
# The registry is GENERATED EVIDENCE, not hand-written prose:
#   - features.toml is the single source (feature ID, summary, status,
#     supported targets, enforcing code, test references, required CI
#     jobs, suite memberships).
#   - The statuses are DERIVED MECHANICALLY from the test-file existence
#     and the suite membership — the generator verifies that every listed
#     test path exists in the tree, that every named suite manifest
#     contains the listed file, and that every named CI job exists in
#     .github/workflows/ci.yml. Any drift FAILS the generation (exit
#     non-zero), so the registry can never claim an artifact that does
#     not exist.
#   - The CI evidence-gate job regenerates the registry and runs
#     `git diff --exit-code`: a hand-edited or drifted committed registry
#     cannot merge.
#
# Status derivation:
#   status = "implemented"  -> "implemented + test-covered" when the
#                              tests/suites verify; "implemented +
#                              unverified" when no tests are listed.
#   status = "partial" | "api-only" | "design" | "unsupported" -> passed
#                              through verbatim.
#   "implemented + run-verified at SHA" is NEVER derived here: it requires
#   the CI status-snapshot artifact (STATUS.txt generated by
#   scripts/gen_status.sh from the TESTED SHA).
#
# Usage: scripts/gen_feature_registry.sh [outfile]
#   outfile defaults to docs/current/feature_registry.md.
# Exit status: 0 when every mechanical check holds and the registry is
# rendered; non-zero (with the file still written, so CI can diff it)
# when a test path, suite entry, or CI job drifted.

set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TOML="$ROOT/features.toml"
WORKFLOW="$ROOT/.github/workflows/ci.yml"
OUT="${1:-$ROOT/docs/current/feature_registry.md}"

if [ ! -f "$TOML" ]; then
  echo "gen_feature_registry: missing features.toml: $TOML" >&2
  exit 1
fi

python3 - "$TOML" "$WORKFLOW" "$OUT" <<'PY'
import json
import os
import re
import sys
import hashlib

toml_path, workflow_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]

# ── TOML parsing: tomllib (3.11+) -> tomli -> the constrained fallback ────
def parse_fallback(text):
    """Parse the constrained features.toml subset:
    comments, [feature."id"] tables, key = "value", key = [...],
    key = [] (arrays may span lines; entries are quoted strings)."""
    features = {}
    current = None
    pending_key = None
    array = None
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("[") and line.endswith("]"):
            if array is not None:
                current[pending_key] = array
                array = None
            header = line[1:-1].strip()
            m = re.match(r'feature\.\s*"([^"]+)"', header)
            if not m:
                raise ValueError("unexpected table header: " + header)
            fid = m.group(1)
            if fid not in features:
                features[fid] = {}
            current = features[fid]
            continue
        if array is not None:
            if line == "]":
                current[pending_key] = array
                array = None
                continue
            m = re.match(r'"((?:[^"\\]|\\.)*)"\s*,?$', line)
            if not m:
                raise ValueError("array entry parse failure: " + line)
            array.append(m.group(1).replace('\\"', '"').replace("\\\\", "\\"))
            continue
        m = re.match(r'([A-Za-z0-9_]+)\s*=\s*"((?:[^"\\]|\\.)*)"\s*$', line)
        if m:
            current[m.group(1)] = m.group(2).replace('\\"', '"').replace("\\\\", "\\")
            continue
        m = re.match(r'([A-Za-z0-9_]+)\s*=\s*\[\s*$', line)
        if m:
            pending_key = m.group(1)
            array = []
            continue
        m = re.match(r'([A-Za-z0-9_]+)\s*=\s*\[\]\s*$', line)
        if m:
            current[m.group(1)] = []
            continue
        raise ValueError("parse failure: " + raw)
    if array is not None:
        current[pending_key] = array
    return features

def parse_toml(text):
    try:
        import tomllib
        return tomllib.loads(text)
    except ImportError:
        pass
    try:
        import tomli
        return tomli.loads(text)
    except ImportError:
        pass
    return parse_fallback(text)

with open(toml_path, "r", encoding="utf-8") as fh:
    doc = parse_toml(fh.read())

features = doc.get("feature", {})
if not features:
    print("gen_feature_registry: no [feature.*] tables in features.toml", file=sys.stderr)
    sys.exit(1)

workflow_text = open(workflow_path, "r", encoding="utf-8").read() if os.path.exists(workflow_path) else ""

def suite_manifest(suite):
    return os.path.join(os.path.dirname(toml_path), "tests", suite, "MANIFEST")

def in_manifest(suite, relpath):
    man = suite_manifest(suite)
    if not os.path.exists(man):
        return False
    base = os.path.basename(relpath)
    with open(man, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            if line.split("\t", 1)[0] == base:
                return True
    return False

def job_exists(job):
    return re.search(r"^  " + re.escape(job) + r":\s*$", workflow_text, re.M) is not None

failures = []
derived = {}
for fid, f in features.items():
    if not isinstance(f, dict):
        continue
    status = f.get("status", "")
    tests = f.get("tests") or []
    suites = f.get("suites") or []
    jobs = f.get("ci_job") or []
    if isinstance(jobs, str):
        jobs = [jobs]

    # mechanical checks: every listed test path must exist; a test that
    # lives in a named suite's directory must be listed in that suite's
    # MANIFEST (tests outside the suite directories verify by existence).
    for t in tests:
        if not os.path.exists(os.path.join(os.path.dirname(toml_path), t)):
            failures.append("feature '%s': listed test path does not exist: %s" % (fid, t))
    for t in tests:
        for s in suites:
            if t.startswith("tests/%s/" % s):
                if not in_manifest(s, t):
                    failures.append(
                        "feature '%s': %s is not listed in tests/%s/MANIFEST"
                        % (fid, t, s))
    for j in jobs:
        if not job_exists(j):
            failures.append("feature '%s': ci_job '%s' is not a job in .github/workflows/ci.yml" % (fid, j))

    # status derivation
    if status == "implemented":
        derived[fid] = ("implemented + test-covered" if tests
                        else "implemented + unverified")
    else:
        derived[fid] = status

# ── render the registry ────────────────────────────────────────────────────
# The rendered file is DETERMINISTIC (no SHA, no timestamp in the body):
# the CI evidence-gate job regenerates it and runs `git diff --exit-code`,
# so any embedded run identity would make every PR's diff non-empty. The
# generation identity (the tested SHA + timestamp) lives in the
# status-snapshot artifact, not in the registry.
import datetime
stamp = datetime.date.today().isoformat()

lines = []
lines.append("# Tangerine Feature Registry")
lines.append("")
lines.append("> **GENERATED EVIDENCE — do not edit by hand.** This document is")
lines.append("> rendered by `scripts/gen_feature_registry.sh` from")
lines.append("> [`features.toml`](../../features.toml), the machine-readable source of")
lines.append("> truth: the feature ID, the status, the supported targets, and the test")
lines.append("> references. The CI evidence-gate job regenerates it and runs")
lines.append("> `git diff --exit-code`, so a hand-edited or drifted registry cannot")
lines.append("> merge. Every feature appears exactly once with exactly one status;")
lines.append("> the statuses are **mechanically derived** (test-file existence + suite")
lines.append("> membership + the declared CI gates), never hand-asserted.")
lines.append("")
lines.append("## How a status is decided")
lines.append("")
lines.append("The generator verifies each row's evidence before it renders:")
lines.append("")
lines.append("- every **test reference** must exist in the tree, and every named")
lines.append("  **suite manifest** (`tests/canary/MANIFEST`, `tests/canary_neg/MANIFEST`,")
lines.append("  `tests/arm64/MANIFEST`) must contain the listed file — a listed artifact")
lines.append("  that does not exist fails the generation;")
lines.append("- every named **CI gate** must be a job in `.github/workflows/ci.yml`;")
lines.append("- `implemented` derives to **implemented + test-covered** (committed test")
lines.append("  artifacts exist) or **implemented + unverified** (no committed test")
lines.append("  artifact), never to run-verified.")
lines.append("")
lines.append("> **Execution honesty — the CI-artifact evidence model.** A committed")
lines.append("> test artifact is a source-state fact; an observed execution is a run")
lines.append("> fact, and they are separate statuses:")
lines.append(">")
lines.append("> - **implemented + test-covered** — the repo ships a committed test")
lines.append(">   artifact that exercises the feature (a manifest-registered canary, an")
lines.append(">   invariant group, a required gate, an `@test` file, or the self-host")
lines.append(">   compiler kernel itself as the workload). It does NOT claim the")
lines.append(">   artifact has run anywhere.")
lines.append("> - **implemented + run-verified at SHA** — a CI artifact proves the")
lines.append(">   execution at the named commit: the CI pipeline runs the harness and")
lines.append(">   the suites and uploads the tested-SHA snapshot — the")
lines.append(">   `status-snapshot` CI artifact (STATUS.txt generated by")
lines.append(">   `scripts/gen_status.sh` from the tested commit + the test-artifact")
lines.append(">   hashes). **No feature holds this status in this snapshot** — the")
lines.append(">   ladder/CI has not run on the tested tree, so there is no observed")
lines.append(">   successful execution at a named SHA.")
lines.append(">")
lines.append("> This registry records only source-state facts, never run results.")
lines.append("")
lines.append("## Legend")
lines.append("")
lines.append("| Status | Meaning |")
lines.append("|--------|---------|")
lines.append("| **implemented + run-verified at SHA** | The compiler/runtime implements the feature AND an observed successful execution of its test artifact at the named commit is proven by a CI artifact (the `status-snapshot` generated by `scripts/gen_status.sh` from the tested SHA). **None in this snapshot** — no ladder/CI run has occurred on the tested tree |")
lines.append("| **implemented + test-covered** | The compiler/runtime implements the feature and a committed test artifact exists (manifest-registered canary, invariant group, required CI gate, `@test` file, or the self-host kernel as workload) that exercises it — but no observed execution at this SHA |")
lines.append("| **implemented + unverified** | The compiler/runtime implements the feature; no committed test artifact exercises it |")
lines.append("| **partial** | A working subset exists; the full feature is not present |")
lines.append("| **API-only** | The std module / interface is declared, but the compiler does not wire it into the pipeline and it is not in the bootstrap closure |")
lines.append("")
lines.append("Non-implemented rows keep their unchanged statuses (outside the")
lines.append("implemented-feature vocabulary): **design** — specified in docs/RFCs")
lines.append("only, no implementation; **unsupported** — explicitly removed or")
lines.append("rejected by the compiler (E100/E106 hard errors).")
lines.append("")
lines.append("## Registry")
lines.append("")
lines.append("| Feature | Status | Targets | Enforcing code | Test / assertion | CI gate |")
lines.append("|---------|--------|---------|----------------|------------------|---------|")

ordered = sorted(features.keys())
for fid in ordered:
    f = features[fid]
    summary = (f.get("summary") or fid).replace("|", "\\|")
    status = derived.get(fid, "?")
    targets = ", ".join(f.get("targets") or [])
    enforcing = (f.get("enforcing") or "—").replace("|", "\\|")
    tests = f.get("tests") or []
    if tests:
        tcell = "; ".join(t.replace("|", "\\|") for t in tests)
    else:
        tcell = "—"
    jobs = f.get("ci_job") or []
    if isinstance(jobs, str):
        jobs = [jobs]
    jcell = "; ".join("`%s`" % j for j in jobs) if jobs else "—"
    lines.append("| `%s` — %s | **%s** | %s | %s | %s | %s |"
                 % (fid, summary, status, targets, enforcing, tcell, jcell))

lines.append("")
lines.append("## Cross-references")
lines.append("")
lines.append("- [Feature Matrix](feature_matrix.md) — Tangerine vs Rust; statuses derive from this generated registry.")
lines.append("- [Grammar](grammar.md) — the implemented grammar, including the E100/E106 rejection surfaces.")
lines.append("- [Language Reference](language.md) — the current dialect (access conventions, views, FFI pointers).")
lines.append("- [Standard Library Reference](stdlib_reference.md) — module surfaces and the migration-complete gate.")
lines.append("- [Memory Model](memory_model.md) — the normative ownership/access model.")
lines.append("- [Concurrency Guide](concurrency.md) — the access/resource concurrency model (threads, async, shared state).")
lines.append("- `scripts/verify_invariants.sh` — the machine-checkable invariant groups (G1–G12) cited above.")
lines.append("- `features.toml` — the machine-readable source this document is generated from.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("*Generated by `scripts/gen_feature_registry.sh` from `features.toml` —")
lines.append(" deterministic output, so the CI evidence-gate job can regenerate it and run")
lines.append(" `git diff --exit-code`. Source-state facts only — no feature holds")
lines.append(" implemented+run-verified at SHA (that status requires the")
lines.append(" `status-snapshot` artifact of a tested-SHA CI run). Do not edit this file by hand.*")
lines.append("")

text = "\n".join(lines)
with open(out_path, "w", encoding="utf-8") as fh:
    fh.write(text)

print("gen_feature_registry: %d feature(s) -> %s" % (len(ordered), out_path))
if failures:
    print("gen_feature_registry: FAILURES (the registry was still written for the CI diff):", file=sys.stderr)
    for f in failures:
        print("  - " + f, file=sys.stderr)
    sys.exit(1)
print("gen_feature_registry: every test path, suite membership and CI job verified")
sys.exit(0)
PY
