#!/usr/bin/env bash
#
# scripts/gen_feature_registry.sh — generate docs/current/feature_registry.md
# from the machine-readable features.toml.
#
# The registry is GENERATED EVIDENCE, not hand-written prose:
#   - features.toml is the single source (feature ID, summary, status,
#     supported targets, enforcing code, test references, required CI
#     jobs, suite memberships, the item-33 experimental gate).
#   - The statuses are DERIVED MECHANICALLY from the test-file existence
#     and the suite membership — the generator verifies that every listed
#     test path exists in the tree, that every named suite manifest
#     contains the listed file, and that every named CI job exists in
#     .github/workflows/ci.yml. Any drift FAILS the generation (exit
#     non-zero), so the registry can never claim an artifact that does
#     not exist.
#   - The item-36 STATUS LADDER is CALCULATED (never typed in
#     features.toml): DECLARED -> IMPLEMENTED -> SEMANTICALLY_CHECKED ->
#     NATIVE_TESTED -> ADVERSARIAL_TESTED -> TARGET_COMPLETE ->
#     EXACT_SHA_VERIFIED -> RELEASE_GATED, derived from the test
#     artifacts' existence (+ the enforcing-code references). The top two
#     positions are RUN facts: EXACT_SHA_VERIFIED and RELEASE_GATED are
#     read from build/release_evidence.json, the release-run evidence
#     file written ONLY by scripts/gen_status.sh --release-evidence —
#     never derived from source.
#   - The CI evidence-gate job regenerates the registry and runs
#     `git diff --exit-code`: a hand-edited or drifted committed registry
#     cannot merge. The generator ALSO regenerates the item-32
#     completeness model (scripts/gen_stdlib_completeness.sh) and the
#     public-API manifest (scripts/gen_api_manifest.sh), so the
#     evidence-gate run keeps every generated evidence artifact in sync
#     (the sweep job diff-gates the committed completeness artifacts).
#
# Status derivation:
#   status = "implemented"  -> "implemented + test-covered" when the
#                              tests/suites verify; "implemented +
#                              unverified" when no tests are listed.
#   status = "partial" | "api-only" | "design" | "unsupported" -> passed
#                              through verbatim.
#   experimental = true     -> the status cell carries the "experimental"
#                              marker (the item-33 stable-subset gate).
#   "implemented + run-verified at SHA" is NEVER derived here: it requires
#   the CI status-snapshot artifact (STATUS.txt generated by
#   scripts/gen_status.sh from the TESTED SHA).
#
# Usage: scripts/gen_feature_registry.sh [outfile] [ladder-json]
#   outfile defaults to docs/current/feature_registry.md.
#   ladder-json (optional) additionally writes the CALCULATED ladder
#   (feature id -> position, source-state facts only) as JSON — consumed
#   by scripts/gen_status.sh --release-evidence, which computes the
#   RELEASE_GATED list from it after the release checks pass.
# Exit status: 0 when every mechanical check holds and the registry is
# rendered; non-zero (with the file still written, so CI can diff it)
# when a test path, suite entry, CI job, or the completeness chain
# drifted.

set -u

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TOML="$ROOT/features.toml"
WORKFLOW="$ROOT/.github/workflows/ci.yml"
OUT="${1:-$ROOT/docs/current/feature_registry.md}"
LADDER_JSON="${2:-}"

if [ ! -f "$TOML" ]; then
  echo "gen_feature_registry: missing features.toml: $TOML" >&2
  exit 1
fi

# ── the item-32 completeness chain (regenerate everything the
# ── evidence-gate touches; the sweep job diff-gates the committed docs).
if ! bash "$ROOT/scripts/gen_stdlib_completeness.sh" "$ROOT/docs/current/stdlib_completeness.md"; then
  echo "gen_feature_registry: the stdlib completeness model FAILED (enumeration / contracts / experimental gating)" >&2
  exit 1
fi
if ! bash "$ROOT/scripts/gen_api_manifest.sh"; then
  echo "gen_feature_registry: the public-API manifest FAILED (extraction health)" >&2
  exit 1
fi

python3 - "$TOML" "$WORKFLOW" "$OUT" "$LADDER_JSON" <<'PY'
import json
import os
import re
import sys

toml_path, workflow_path, out_path, ladder_json_path = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]

# ── TOML parsing: tomllib (3.11+) -> tomli -> the constrained fallback ────
def parse_fallback(text):
    """Parse the constrained features.toml subset:
    comments, [feature."id"] tables, key = "value", key = [...],
    key = [] (arrays may span lines; entries are quoted strings)."""
    features = {}
    current = None
    pending_key = None
    array = None
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        if line.startswith("[") and line.endswith("]"):
            if array is not None:
                current[pending_key] = array
                array = None
            header = line[1:-1].strip()
            m = re.match(r'feature\.\s*"([^"]+)"', header)
            if not m:
                raise ValueError("unexpected table header: " + header)
            fid = m.group(1)
            if fid not in features:
                features[fid] = {}
            current = features[fid]
            continue
        if array is not None:
            if line == "]":
                current[pending_key] = array
                array = None
                continue
            m = re.match(r'"((?:[^"\\]|\\.)*)"\s*,?$', line)
            if not m:
                raise ValueError("array entry parse failure: " + line)
            array.append(m.group(1).replace('\\"', '"').replace("\\\\", "\\"))
            continue
        m = re.match(r'([A-Za-z0-9_]+)\s*=\s*"((?:[^"\\]|\\.)*)"\s*$', line)
        if m:
            current[m.group(1)] = m.group(2).replace('\\"', '"').replace("\\\\", "\\")
            continue
        m = re.match(r'([A-Za-z0-9_]+)\s*=\s*\[\s*$', line)
        if m:
            pending_key = m.group(1)
            array = []
            continue
        m = re.match(r'([A-Za-z0-9_]+)\s*=\s*\[\]\s*$', line)
        if m:
            current[m.group(1)] = []
            continue
        raise ValueError("parse failure: " + raw)
    if array is not None:
        current[pending_key] = array
    return features

def parse_toml(text):
    try:
        import tomllib
        return tomllib.loads(text)
    except ImportError:
        pass
    try:
        import tomli
        return tomli.loads(text)
    except ImportError:
        pass
    return parse_fallback(text)

with open(toml_path, "r", encoding="utf-8") as fh:
    doc = parse_toml(fh.read())

features = doc.get("feature", {})
if not features:
    print("gen_feature_registry: no [feature.*] tables in features.toml", file=sys.stderr)
    sys.exit(1)

workflow_text = open(workflow_path, "r", encoding="utf-8").read() if os.path.exists(workflow_path) else ""

def suite_manifest(suite):
    return os.path.join(os.path.dirname(toml_path), "tests", suite, "MANIFEST")

def in_manifest(suite, relpath):
    man = suite_manifest(suite)
    if not os.path.exists(man):
        return False
    base = os.path.basename(relpath)
    with open(man, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            if line.split("\t", 1)[0] == base:
                return True
    return False

def job_exists(job):
    return re.search(r"^  " + re.escape(job) + r":\s*$", workflow_text, re.M) is not None

failures = []
derived = {}
ladder = {}

# ── the release-run evidence (EXACT_SHA_VERIFIED / RELEASE_GATED) ────────
# build/release_evidence.json is written ONLY by scripts/gen_status.sh
# --release-evidence from the tested-SHA run artifacts. The ladder's top
# two positions are READ from it; they are never derived from source.
release_evidence = {}
evidence_path = os.path.join(os.path.dirname(toml_path), "build", "release_evidence.json")
if os.path.exists(evidence_path):
    try:
        with open(evidence_path, "r", encoding="utf-8") as fh:
            release_evidence = json.load(fh)
    except Exception:
        release_evidence = {}
for fid, f in features.items():
    if not isinstance(f, dict):
        continue
    status = f.get("status", "")
    tests = f.get("tests") or []
    suites = f.get("suites") or []
    jobs = f.get("ci_job") or []
    if isinstance(jobs, str):
        jobs = [jobs]

    # mechanical checks: every listed test path must exist; a test that
    # lives in a named suite's directory must be listed in that suite's
    # MANIFEST (tests outside the suite directories verify by existence).
    for t in tests:
        if not os.path.exists(os.path.join(os.path.dirname(toml_path), t)):
            failures.append("feature '%s': listed test path does not exist: %s" % (fid, t))
    for t in tests:
        for s in suites:
            if t.startswith("tests/%s/" % s):
                if not in_manifest(s, t):
                    failures.append(
                        "feature '%s': %s is not listed in tests/%s/MANIFEST"
                        % (fid, t, s))
    for j in jobs:
        if not job_exists(j):
            failures.append("feature '%s': ci_job '%s' is not a job in .github/workflows/ci.yml" % (fid, j))

    # status derivation (the declared status stays the input; the
    # item-36 LADDER is calculated below from the artifact existence).
    if status == "implemented":
        derived[fid] = ("implemented + test-covered" if tests
                        else "implemented + unverified")
    else:
        derived[fid] = status

    # ── the item-36 status ladder (CALCULATED, never typed) ──────────────
    # The ladder positions and their artifact-existence derivations:
    LADDER = ["DECLARED", "IMPLEMENTED", "SEMANTICALLY_CHECKED",
              "NATIVE_TESTED", "ADVERSARIAL_TESTED", "TARGET_COMPLETE",
              "EXACT_SHA_VERIFIED", "RELEASE_GATED"]
    LADDER_IDX = {name: i for i, name in enumerate(LADDER)}

    def is_native_artifact(t):
        # a tests/**/*.tg file (canary / @test — runs natively) or a
        # tests/run_*.sh gate that executes tests.
        base = os.path.basename(t)
        return (t.startswith("tests/") and
                (t.endswith(".tg") or (base.startswith("run_") and t.endswith(".sh"))))

    def is_adversarial_artifact(t):
        # the negative/fuzz/differential/negative-ABI suites and gates.
        return (re.search(r"tests/(canary_neg|fuzz|differential|slice_safety)/", t) or
                re.search(r"(canary_neg|neg|fuzz|differential|adversarial|litmus)", t)) is not None

    def enforcing_refs_ok(text):
        # every file/dir reference in the enforcing text must exist.
        refs = re.findall(r"([A-Za-z0-9_./-]+\.(?:tg|swift|sh|py|c|h|md|json|toml))", text or "")
        refs += re.findall(r"([A-Za-z0-9_./-]+/)\b", text or "")
        for r in refs:
            if not os.path.exists(os.path.join(os.path.dirname(toml_path), r)):
                return False
        return bool(refs)

    pos = 0  # the highest ladder position whose evidence holds
    # The ladder positions above DECLARED are only reachable when the
    # DECLARED status asserts implementation (implemented/partial): an
    # unsupported/design/api-only row is DECLARED — its rejection surface
    # is implemented, but the FEATURE is not.
    if status in ("implemented", "partial"):
        # IMPLEMENTED — the declared status asserts implementation AND the
        # enforcing-code references resolve to real files.
        if enforcing_refs_ok(f.get("enforcing")):
            pos = max(pos, LADDER_IDX["IMPLEMENTED"])
        # SEMANTICALLY_CHECKED — every listed test artifact exists (committed).
        if tests and all(os.path.exists(os.path.join(os.path.dirname(toml_path), t)) for t in tests):
            pos = max(pos, LADDER_IDX["SEMANTICALLY_CHECKED"])
            # NATIVE_TESTED — at least one listed artifact is a native one.
            if any(is_native_artifact(t) for t in tests):
                pos = max(pos, LADDER_IDX["NATIVE_TESTED"])
                # ADVERSARIAL_TESTED — at least one listed artifact is adversarial.
                if any(is_adversarial_artifact(t) for t in tests):
                    pos = max(pos, LADDER_IDX["ADVERSARIAL_TESTED"])
                # TARGET_COMPLETE — every declared target is SERVED (the honest
                # capability matrix; windows/wasm32 are not served) AND the
                # feature holds a native artifact.
                served = {"aarch64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-apple-darwin"}
                if all(tgt in served for tgt in (f.get("targets") or [])) and (f.get("targets") or []):
                    pos = max(pos, LADDER_IDX["TARGET_COMPLETE"])
    # EXACT_SHA_VERIFIED / RELEASE_GATED — RUN facts: read ONLY from the
    # release-evidence file (written only by scripts/gen_status.sh
    # --release-evidence from the tested-SHA run artifacts).
    if pos >= LADDER_IDX["TARGET_COMPLETE"] and release_evidence:
        sha = release_evidence.get("tested_sha") or ""
        if re.fullmatch(r"[0-9a-f]{7,40}", sha) and release_evidence.get("artifact_hashes"):
            pos = max(pos, LADDER_IDX["EXACT_SHA_VERIFIED"])
    if fid in (release_evidence.get("release_gated_features") or []):
        pos = LADDER_IDX["RELEASE_GATED"]
    ladder[fid] = LADDER[pos]

# ── render the registry ────────────────────────────────────────────────────
# The rendered file is DETERMINISTIC (no SHA, no timestamp in the body):
# the CI evidence-gate job regenerates it and runs `git diff --exit-code`,
# so any embedded run identity would make every PR's diff non-empty. The
# generation identity (the tested SHA + timestamp) lives in the
# status-snapshot artifact, not in the registry.
import datetime
stamp = datetime.date.today().isoformat()

lines = []
lines.append("# Tangerine Feature Registry")
lines.append("")
lines.append("> **GENERATED EVIDENCE — do not edit by hand.** This document is")
lines.append("> rendered by `scripts/gen_feature_registry.sh` from")
lines.append("> [`features.toml`](../../features.toml), the machine-readable source of")
lines.append("> truth: the feature ID, the status, the supported targets, and the test")
lines.append("> references. The CI evidence-gate job regenerates it and runs")
lines.append("> `git diff --exit-code`, so a hand-edited or drifted registry cannot")
lines.append("> merge. Every feature appears exactly once with exactly one status;")
lines.append("> the statuses are **mechanically derived** (test-file existence + suite")
lines.append("> membership + the declared CI gates), never hand-asserted, and the")
lines.append("> item-36 **status ladder** is **calculated**, never typed.")
lines.append("")
lines.append("## How a status is decided")
lines.append("")
lines.append("The generator verifies each row's evidence before it renders:")
lines.append("")
lines.append("- every **test reference** must exist in the tree, and every named")
lines.append("  **suite manifest** (`tests/canary/MANIFEST`, `tests/canary_neg/MANIFEST`,")
lines.append("  `tests/arm64/MANIFEST`) must contain the listed file — a listed artifact")
lines.append("  that does not exist fails the generation;")
lines.append("- every named **CI gate** must be a job in `.github/workflows/ci.yml`;")
lines.append("- `implemented` derives to **implemented + test-covered** (committed test")
lines.append("  artifacts exist) or **implemented + unverified** (no committed test")
lines.append("  artifact), never to run-verified.")
lines.append("")
lines.append("## The status ladder (the reviewer's item 36)")
lines.append("")
lines.append("The ladder position is CALCULATED from the committed evidence (the")
lines.append("typed `status` in features.toml is only the DECLARED input):")
lines.append("")
lines.append("| Position | Derivation (what evidence must exist) |")
lines.append("|----------|----------------------------------------|")
lines.append("| `DECLARED` | the row exists in features.toml |")
lines.append("| `IMPLEMENTED` | the declared status is implemented/partial AND every enforcing-code file/dir reference exists in the tree |")
lines.append("| `SEMANTICALLY_CHECKED` | every listed test artifact exists (committed; std modules additionally parse-clean under the E106 sweep) |")
lines.append("| `NATIVE_TESTED` | at least one listed artifact is a native behavior artifact (a `tests/**/*.tg` canary/@test file or a `tests/run_*.sh` gate) |")
lines.append("| `ADVERSARIAL_TESTED` | at least one listed artifact is adversarial (canary_neg / fuzz / differential / slice_safety / *neg* / *litmus*) |")
lines.append("| `TARGET_COMPLETE` | every declared target is a SERVED target (aarch64-apple-darwin, x86_64-unknown-linux-gnu, x86_64-apple-darwin — windows/wasm32 are NOT served) AND a native artifact exists |")
lines.append("| `EXACT_SHA_VERIFIED` | run evidence at a named SHA: `build/release_evidence.json` (written ONLY by `scripts/gen_status.sh --release-evidence`) carries the tested sha + artifact hashes |")
lines.append("| `RELEASE_GATED` | the feature is listed in the release-evidence file's `release_gated_features` — **never derivable from source**, only from the release-run evidence |")
lines.append("")
lines.append("The ladder is a monotone chain: a feature at position N holds every")
lines.append("position below N. The top two positions are RUN facts; this")
lines.append("snapshot records source-state facts only, so nothing above")
lines.append("`TARGET_COMPLETE` appears here unless the release-evidence file is")
lines.append("present in the tree.")
lines.append("")
lines.append("> **Execution honesty — the CI-artifact evidence model.** A committed")
lines.append("> test artifact is a source-state fact; an observed execution is a run")
lines.append("> fact, and they are separate statuses:")
lines.append(">")
lines.append("> - **implemented + test-covered** — the repo ships a committed test")
lines.append(">   artifact that exercises the feature (a manifest-registered canary, an")
lines.append(">   invariant group, a required gate, an `@test` file, or the self-host")
lines.append(">   compiler kernel itself as the workload). It does NOT claim the")
lines.append(">   artifact has run anywhere.")
lines.append("> - **implemented + run-verified at SHA** — a CI artifact proves the")
lines.append(">   execution at the named commit: the CI pipeline runs the harness and")
lines.append(">   the suites and uploads the tested-SHA snapshot — the")
lines.append(">   `status-snapshot` CI artifact (STATUS.txt generated by")
lines.append(">   `scripts/gen_status.sh` from the tested commit + the test-artifact")
lines.append(">   hashes). **No feature holds this status in this snapshot** — the")
lines.append(">   ladder/CI has not run on the tested tree, so there is no observed")
lines.append(">   successful execution at a named SHA.")
lines.append(">")
lines.append("> This registry records only source-state facts, never run results.")
lines.append("")
lines.append("## Legend")
lines.append("")
lines.append("| Status | Meaning |")
lines.append("|--------|---------|")
lines.append("| **implemented + run-verified at SHA** | The compiler/runtime implements the feature AND an observed successful execution of its test artifact at the named commit is proven by a CI artifact (the `status-snapshot` generated by `scripts/gen_status.sh` from the tested SHA). **None in this snapshot** — no ladder/CI run has occurred on the tested tree |")
lines.append("| **implemented + test-covered** | The compiler/runtime implements the feature and a committed test artifact exists (manifest-registered canary, invariant group, required CI gate, `@test` file, or the self-host kernel as workload) that exercises it — but no observed execution at this SHA |")
lines.append("| **implemented + unverified** | The compiler/runtime implements the feature; no committed test artifact exercises it |")
lines.append("| **partial** | A working subset exists; the full feature is not present |")
lines.append("| **API-only** | The std module / interface is declared, but the compiler does not wire it into the pipeline and it is not in the bootstrap closure |")
lines.append("")
lines.append("Non-implemented rows keep their unchanged statuses (outside the")
lines.append("implemented-feature vocabulary): **design** — specified in docs/RFCs")
lines.append("only, no implementation; **unsupported** — explicitly removed or")
lines.append("rejected by the compiler (E100/E106 hard errors).")
lines.append("")
lines.append("## The experimental gate (the reviewer's item 33)")
lines.append("")
lines.append("A row marked **experimental** is a platform-only surface whose targets")
lines.append("are unsupported/API-only (the stable-subset policy): the feature and")
lines.append("its std modules (the row's `modules = [...]`) carry parse-clean")
lines.append("evidence only and are **explicitly excluded from the shipped-std")
lines.append("behavior claims** — see the [Stdlib Completeness Model](stdlib_completeness.md)")
lines.append("and the contracts manifest (`docs/current/stdlib_contracts.toml`). The")
lines.append("generator cross-checks the two registries: every experimental module")
lines.append("must be listed in exactly one experimental row, and every module a")
lines.append("row lists must be experimental in the contracts manifest.")
lines.append("")
lines.append("## Registry")
lines.append("")
lines.append("| Feature | Status | Ladder | Targets | Enforcing code | Test / assertion | CI gate |")
lines.append("|---------|--------|--------|---------|----------------|------------------|---------|")

ordered = sorted(features.keys())
for fid in ordered:
    f = features[fid]
    summary = (f.get("summary") or fid).replace("|", "\\|")
    status = derived.get(fid, "?")
    if f.get("experimental"):
        status = status + " — experimental"
    ladder_pos = ladder.get(fid, "DECLARED")
    targets = ", ".join(f.get("targets") or [])
    enforcing = (f.get("enforcing") or "—").replace("|", "\\|")
    tests = f.get("tests") or []
    if tests:
        tcell = "; ".join(t.replace("|", "\\|") for t in tests)
    else:
        tcell = "—"
    jobs = f.get("ci_job") or []
    if isinstance(jobs, str):
        jobs = [jobs]
    jcell = "; ".join("`%s`" % j for j in jobs) if jobs else "—"
    lines.append("| `%s` — %s | **%s** | `%s` | %s | %s | %s | %s |"
                 % (fid, summary, status, ladder_pos, targets, enforcing, tcell, jcell))

lines.append("")
lines.append("## Cross-references")
lines.append("")
lines.append("- [Feature Matrix](feature_matrix.md) — Tangerine vs Rust; statuses derive from this generated registry.")
lines.append("- [Stdlib Completeness Model](stdlib_completeness.md) — the item-32 verification families + the enumeration gate.")
lines.append("- [Grammar](grammar.md) — the implemented grammar, including the E100/E106 rejection surfaces.")
lines.append("- [Language Reference](language.md) — the current dialect (access conventions, views, FFI pointers).")
lines.append("- [Standard Library Reference](stdlib_reference.md) — module surfaces and the migration-complete gate.")
lines.append("- [Memory Model](memory_model.md) — the normative ownership/access model.")
lines.append("- [Concurrency Guide](concurrency.md) — the access/resource concurrency model (threads, async, shared state).")
lines.append("- `scripts/verify_invariants.sh` — the machine-checkable invariant groups (G1–G12) cited above.")
lines.append("- `features.toml` — the machine-readable source this document is generated from.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("*Generated by `scripts/gen_feature_registry.sh` from `features.toml` —")
lines.append(" deterministic output, so the CI evidence-gate job can regenerate it and run")
lines.append(" `git diff --exit-code`. Source-state facts only — no feature holds")
lines.append(" implemented+run-verified at SHA and nothing above TARGET_COMPLETE appears")
lines.append(" without `build/release_evidence.json` (the release-run evidence written")
lines.append(" only by `scripts/gen_status.sh --release-evidence`; RELEASE_GATED is")
lines.append(" never derived from source). Do not edit this file by hand.*")
lines.append("")

text = "\n".join(lines)
with open(out_path, "w", encoding="utf-8") as fh:
    fh.write(text)

if ladder_json_path:
    with open(ladder_json_path, "w", encoding="utf-8") as fh:
        json.dump({"ladder": ladder}, fh, indent=2, sort_keys=True)
        fh.write("\n")

print("gen_feature_registry: %d feature(s) -> %s" % (len(ordered), out_path))
if failures:
    print("gen_feature_registry: FAILURES (the registry was still written for the CI diff):", file=sys.stderr)
    for f in failures:
        print("  - " + f, file=sys.stderr)
    sys.exit(1)
print("gen_feature_registry: every test path, suite membership and CI job verified")
sys.exit(0)
PY
